healthcheck NOK

diff --git a/backend/Dockerfile b/backend/Dockerfile
--- a/backend/Dockerfile
+++ b/backend/Dockerfile
@@ -5,9 +5,13 @@ FROM python:3.11-slim
 # for DEBUG only: dialog, curl, apt-utils (to be removed for PROD)
 # Layer reduction: group all apt-get into 1 liner
 # DEV mode only (remove for PROD): Adding nano
+# PROD: keep PostgreSQL client tools for "pg_isready"
 RUN apt-get update && \
     apt-get install -y nano dialog apt-utils postgresql-client curl && \
     rm -rf /var/lib/apt/lists/*
+
+# for python: alpine
+# RUN apk add --no-cache postgresql-client 
 
 # DEBUG
 # COPY backend/debug.sh /debug.sh
@@ -22,8 +26,9 @@ COPY backend/requirements.txt .
 # copy main and __init__.py files into the container at /code/app
 COPY backend/app .
 
+# workaround for podman v4 (without healthchecks)
 # COPY backend/wait-for-db.sh .
-COPY backend/wait-for-db.sh .
+
 
 # Install any dependencies specified in requirements.txt
 # options:
@@ -31,12 +36,19 @@ COPY backend/wait-for-db.sh .
 # --proxy-headers is used to trust the headers from the reverse proxy (Traefik)
 RUN pip install --no-cache-dir --upgrade -r requirements.txt
 
-# Expose the port that Fastapi will run on
+# Exposing the port that Fastapi will run on
 EXPOSE "8001"
 
 # Healthcheck workaround
 # HEALTHCHECK CMD pg_isready -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" || exit 1
-ENTRYPOINT ["./wait-for-db.sh"]
+# ENTRYPOINT ["./wait-for-db.sh"]
+
+# Backend tests DB - this is the ONLY health check needed
+# HEALTHCHECK --interval=15s --timeout=10s --start-period=40s --retries=3 \
+#   CMD pg_isready -h "$POSTGRES_DB_HOST" -p "$POSTGRES_DB_PORT" -U "$POSTGRES_DB_USER" || exit 1
+
+HEALTHCHECK --interval=15s --timeout=10s --start-period=40s --retries=3 \
+  CMD ["pg_isready", "-h", "$POSTGRES_DB_HOST", "-p", "$POSTGRES_DB_PORT", "-U", "$POSTGRES_DB_USER"]
 
 # Command to run the backend application using Uvicorn
 # PROD (no auto reload): CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"]
@@ -44,3 +56,6 @@ ENTRYPOINT ["./wait-for-db.sh"]
 # NOTE: could be flagged as below for DEV/STAGING/PROD: 
 # CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"%%RELOAD_FLAG%%]
 CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001", "--reload"]
+
+# OR:
+# ENTRYPOINT ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"]
